fix(Utilities): update VR namespace to be XR
In Unity 5.5.4 you get this error:
`Assets/VRTK/Source/Scripts/Utilities/VRTK_SharedMethods.cs(359,20):
 error CS0103: The name 'VRStats' does not exist in the current context`

The error disappears changing `VRStats` to `XRStats`.